module.exports = {
  "_id": "69931cb3db02afb83c71d346",
  "currency": {
    "name": "USD",
    "symbol": "$",
    "countryCode": "US",
    "currencyCode": "$",
    "isDefault": true
  },
  "privacyPolicyLink": "<h4>Privacy Policy for Figgy</h4><h4><br></h4><h5>How We Use Your Information</h5><h6>Personal Information:</h6><p><span style=\"color: rgb(187, 187, 187);\">We use your email address for account management and to communicate with you about updates or important information. </span></p><h6>Usage Data:</h6><p><span style=\"color: rgb(187, 187, 187); font-family: Helvetica, Arial, sans-serif; font-size: 13px; font-weight: 400;\">We analyze usage patterns to improve our app's content and user experience. </span></p><h6>Device Information:</h6><p><span style=\"color: rgb(187, 187, 187);\">We use device information for technical purposes, such as troubleshooting and ensuring compatibility.</span></p><h6>Information Sharing</h6><p><span style=\"color: rgb(187, 187, 187);\">We do not sell, trade, or otherwise transfer your personally identifiable information to third parties. We may share aggregated and anonymized data for statistical purposes.</span></p><h6>Security</h6><p><span style=\"color: rgb(187, 187, 187);\">We take reasonable measures to protect your personal information from unauthorized access or disclosure. However, no method of transmission over the Internet or electronic storage is completely secure. </span></p><h6>Your Choices</h6><p><span style=\"color: rgb(187, 187, 187);\">You can manage your account settings and preferences within the app. You may opt out of promotional emails at any time by following the unsubscribe instructions in the email. </span></p><h6>Changes to This Privacy Policy</h6><p><span style=\"color: rgb(187, 187, 187);\">We may update this Privacy Policy from time to time. Any changes will be posted on this page, and the \"Last Updated\" date will be revised accordingly. </span></p><h6>Contact Us</h6><ol><li><span style=\"color: rgb(187, 187, 187);\">If you have any questions or concerns about this Privacy Policy, please contact us at [your contact email]. By using Wallki, you agree to the terms outlined in this Privacy Policy.</span></li></ol>",
  "termsOfUsePolicyLink": "<h4>Terms and Condition for Figgy</h4><h4><br></h4><h5>How We Use Your Information</h5><h6>Personal Information:</h6><p><span style=\"color: rgb(187, 187, 187);\">We use your email address for account management and to communicate with you about updates or important information. </span></p><h6>Usage Data:</h6><p><span style=\"color: rgb(187, 187, 187);\">We analyze usage patterns to improve our app's content and user experience. </span></p><h6>Device Information:</h6><p><span style=\"color: rgb(187, 187, 187);\">We use device information for technical purposes, such as troubleshooting and ensuring compatibility.</span></p><h6>Information Sharing</h6><p><span style=\"color: rgb(187, 187, 187);\">We do not sell, trade, or otherwise transfer your personally identifiable information to third parties. We may share aggregated and anonymized data for statistical purposes.</span></p><h6>Security</h6><p><span style=\"color: rgb(187, 187, 187);\">We take reasonable measures to protect your personal information from unauthorized access or disclosure. However, no method of transmission over the Internet or electronic storage is completely secure. </span></p><h6>Your Choices</h6><p><span style=\"color: rgb(187, 187, 187);\">You can manage your account settings and preferences within the app. You may opt out of promotional emails at any time by following the unsubscribe instructions in the email. </span></p><h6>Contact Us</h6><ol><li><span style=\"color: rgb(187, 187, 187);\">If you have any questions or concerns about this Privacy Policy, please contact us at [your contact email]. By using Wallki, you agree to the terms outlined in this Privacy Policy.</span></li></ol><p><br></p>",
  "googlePlayEnabled": false,
  "stripeEnabled": true,
  "stripePublishableKey": "pk_test_51PnZpxCgbHHJtm7RPVLjX28kr3mQGhHobJ1WaCGKBNh9cWZKLJJdu5f1EltNyjNVzcdQSYgJfizsbbC2RP987rTE00pdwG8KyZ",
  "stripeSecretKey": "sk_test_51PnZpxCgbHHJtm7RDtzCYMoBhYZRAzexHtTEEhQW3AWcZkxMIoDiRq5gv9IaLrgkhUOoJN0oqpA86S7LTpCo47Sy00in4p6AjQ",
  "razorpayEnabled": true,
  "razorpayId": "RAZOR PAY ID",
  "razorpaySecretKey": "rzp_test_SjZz9HC7RGCfCb",
  "flutterwaveEnabled": true,
  "flutterwaveId": "FLWPUBK_TEST-cdc51a4df113a91fe33a914eaf8d1c75-X",
  "loginBonus": 5500,
  "isDemoData": true,
  "minCoinsToConvert": 1000,
  "minCoinsForUserPayout": 1,
  "minCoinsForHostPayout": 100,
  "minCoinsForAgencyPayout": 10,
  "maxFreeChatMessages": 1,
  "privateKey": {
    "type": "service_account",
    "project_id": "demo-123",
    "private_key_id": "3ff5c810db4501d40876c696318313b7a434bab2e4c",
    "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCG2ZOL50Ack/ZL\nyz4Vv8RZPzo9NoahZ9R65WI8l02oWWb9Ba1fEF8c4sxXvwZuBW8pMpcN1wwxFGOD\nZe2XHNZWTL7cSz8R7Qp8c3voAp1rEs+FTaixgE98pzfuG885Zev2xWk2EBcAgGxE\nK2+Gt17w3NxCBSZIYUmKt0jwhp7jjLTcG6WF5qSyCqcWgxu1Od9qBN6AWFfcV1g1\n9Sj9N/GHCSJq60hgNB/Xq03svDPEg2eu7W4Qvwnz7aJC+Fkue2NSGTZV9O4ynHF2\nr2bsOKqM7rDvEYzDlabB/oqR5UmeI9cV0KBQPyIclxQrJXs3dcZGw9HZzt6UHSG6\nQDKBfHb7AgMBAAECggEAMTPlNqhnh6XjOa+MVTI16dx8mwYwpGb2q+rTZ8lLMBCC\n1/KA2k1mbus/5QpRxcYc07reS9H55FSMpM6FnNwMRsvU3htkhV1otJUMklCV8JIZ\n/wkhcrafChwXd71U5JwQN2e7ZlsDkY7KMitpE44HybnEciBf4gwBYehTaFOuWNcg\nL9+0T9sP8lFvfbAPJwZhotNnsXGmiNjSlqNvsN3Kn1JKC5EApjop4oVtQN2O16AR\natRYkOSvYIZHv2Qv6c5/RVOKF+u8LsWiTkS1HXUdNZPLXLZU+kcFEmy0DofY5iMk\npXEaP6VXu9GIDGkFo1kL4XvJ0/Af0GBwL9KfrFtI8QKBgQC9YhB8r8ZJL3DuGcqj\nAmpWCKKOCxc7lajE7rjFt8z9iwhmeDcnqfg9OO2WmsQ00o+X2ZiuH/Cefw9H+mSk\nQ3H2dl1b1x6Ro6uW8uU1TO0iEX6pFPc9zgVZXCFWP99Pt1cv2Ow2Gp7iAvZXpL+8\nhLhS0UYIRel9OiGqkARAi65QMQKBgQC2SM3MPgFQJFlJfGxH3m+gv6yNgOdgIlqK\np738yENU1m6ii4QomXg/hEzONhD8cYGil5amWfn2WDqo3elVPcmXeAn9aZq8LR03\nl1f4e/Ke2uO7r6stCB3e6Qx7HrpfkCLn8pIUpvi5O70eYC1merL3uj80NDxbJGXH\nGgRd13n66wKBgDK525SqOEBOFr+P5Pj4oqbctT26tsRc99GX56H980hOPzfDJ3LW\nUgmEAA+A8OD9LT0NKZoqL/ckLWGoLeDZt+K+HY+F9UgpQMKz2LUIH9QqP3Tmirrh\nPgmLZdqGTTg68X19aveq9bev92/OTxUdr4lvSITaxQmn0nCvFpR7VXthAoGASRsx\nznQfurCZTqukEb7YLjQxVB8arKeagHl97N+0gVXu0Sn7Ov0yCOdalmmArn4na7o4\nJUd4xJ/mBsvZROKe8yyldQjhkg7V5PHBylqLl8JaC3AMyuaydDArXUWZobIBDd1v\nUPEWV9PpqUERdERJeqkrqBg7DKKwXwXEMo600TkCgYEAhWX4Qa0sKlu1CKbOCWPW\n2Bjg8ajwlEisv4APvPH5BnP13gkoj8SFgkMCGW08PIq8jf3zVZI8S6dq8XeFG0Uo\nkg4DZur803xH26sualTvOEsioxNGY/9UxxBAkAam6Y02VFNKq9VA7A9GGsoK8913\n4DdzX2VSFjpNqIpi4NUAwJY=\n-----END PRIVATE KEY-----\n",
    "client_email": "firebase-adminsdk-fbsvc@demo-123.iam.gserviceaccount.com",
    "client_id": "1011940813696339872633919",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40figgy-3139d.iam.gserviceaccount.com",
    "universe_domain": "googleapis.com"
  },
  "createdAt": "2025-03-17T09:22:56.775Z",
  "updatedAt": "2025-06-20T09:28:01.028Z",
  "adminCommissionRate": 20,
  "agoraAppCertificate": "agoraAppCertificate",
  "agoraAppId": "agoraAppId",
  "audioPrivateCallRate": 10,
  "chatInteractionRate": 11,
  "femaleRandomCallRate": 30,
  "generalRandomCallRate": 20,
  "isAppEnabled": true,
  "maleRandomCallRate": 20,
  "videoPrivateCallRate": 10,
  "isAutoRefreshEnabled": false,
  "cashfreeAndroidEnabled": true,
  "cashfreeClientId": "cashfreeClientId",
  "cashfreeClientSecret": "cashfreeClientSecret",
  "cashfreeIosEnabled": false,
  "paypalAndroidEnabled": true,
  "paypalClientId": "paypalClientId",
  "paypalIosEnabled": false,
  "paypalSecretKey": "paypalSecretKey",
  "paystackAndroidEnabled": true,
  "paystackIosEnabled": false,
  "paystackPublicKey": "paystackPublicKey",
  "paystackSecretKey": "paystackSecretKey",
  "flutterwaveIosEnabled": false,
  "googlePayIosEnabled": false,
  "razorpayIosEnabled": false,
  "stripeIosEnabled": false,
  "androidAppLink": "androidAppLink",
  "androidAppVersion": "1.0.0",
  "iosAppLink": "iosAppLink",
  "iosAppVersion": "1.0.0",
  "secretKey": "meetme_secret_key_2024"
};